= Cheatsheets

[[AccessLogOptions]]
== AccessLogOptions


[cols=">25%,^25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[enabled]]`enabled`|`Boolean`|
+++
Sets if logging access to the Knot.x HTTP server is enabled or not. Default is enabled ('true')
+++
|[[format]]`format`|`link:enums.html#LoggerFormat[LoggerFormat]`|
+++
Set format of access log. Default is <strong>LoggerFormat.DEFAULT</strong>.
 Available values are:
 <ul>
   <li>DEFAULT <br/>
      <i>remote-client</i> - - [<i>timestamp</i>] "<i>method</i> <i>uri</i> <i>version</i>" <i>status</i> <i>content-length</i> "<i>referrer</i>" "<i>user-agent</i>
   </li>
   <li>SHORT <br/>
      <i>remote-client</i> - <i>method</i> <i>uri</i> <i>version</i> <i>status</i> <i>content-length</i> <i>duration</i> ms
   </li>
   <li>TINY <br/>
      <i>method</i> <i>uri</i> <i>status</i> - <i>content-length</i> <i>duration</i>
   </li>
 </ul>
+++
|[[immediate]]`immediate`|`Boolean`|
+++
Configure when to collect access log. True if after request arrives, false after sending response.
+++
|===

[[KnotxCSRFOptions]]
== KnotxCSRFOptions


[cols=">25%,^25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[cookieName]]`cookieName`|`String`|
+++
Set the name of the CSRF cookie
+++
|[[cookiePath]]`cookiePath`|`String`|
+++
Set of the path of the CSRF cookie
+++
|[[headerName]]`headerName`|`String`|
+++
Set the CSRF token header name
+++
|[[secret]]`secret`|`String`|
+++
Set the secret used to generate CSRF token
+++
|[[timeout]]`timeout`|`Number (long)`|
+++
Set the timeout of the CSRF token
+++
|===

[[KnotxFlowSettings]]
== KnotxFlowSettings


[cols=">25%,^25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[assembler]]`assembler`|`String`|
+++
Sets the event bus address of the assembler verticle. Default is knotx.core.assembler
+++
|[[repositories]]`repositories`|`Array of link:dataobjects.html#RepositoryEntry[RepositoryEntry]`|
+++
Sets the list of RepositoryEntry items
+++
|[[responseProvider]]`responseProvider`|`String`|
+++
Sets the event bus address of the Custom Flow' response provider verticle. Default is 'knotx.gateway.responseprovider'
+++
|[[routing]]`routing`|`link:dataobjects.html#MethodRoutingEntries[MethodRoutingEntries]`|
+++
Set of HTTP method based routing entries, describing communication between Knots
 <pre>routing": {"GET": {}, "POST": {}}</pre>
+++
|[[splitter]]`splitter`|`String`|
+++
Sets the event bus address of the splitter verticle. Default is knotx.core.splitter
+++
|===

[[KnotxServerOptions]]
== KnotxServerOptions

++++
 Describes a Knot.x HTTP Server configuration
++++
'''

[cols=">25%,^25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[accessLog]]`accessLog`|`link:dataobjects.html#AccessLogOptions[AccessLogOptions]`|
+++
Set the access log options
+++
|[[allowedResponseHeaders]]`allowedResponseHeaders`|`Array of String`|
+++
Set the set of response headers that can be returned by the Knot.x server
+++
|[[csrfConfig]]`csrfConfig`|`link:dataobjects.html#KnotxCSRFOptions[KnotxCSRFOptions]`|
+++
Set the CSRF configuration of the Knot.x server
+++
|[[customFlow]]`customFlow`|`link:dataobjects.html#KnotxFlowSettings[KnotxFlowSettings]`|
+++
Set the Custom Flow configuration
+++
|[[customResponseHeader]]`customResponseHeader`|`link:dataobjects.html#CustomHttpHeader[CustomHttpHeader]`|
+++
Set the custom response header returned by the Knot.x
+++
|[[defaultFlow]]`defaultFlow`|`link:dataobjects.html#KnotxFlowSettings[KnotxFlowSettings]`|
+++
Set the Default flow configuration
+++
|[[deliveryOptions]]`deliveryOptions`|`link:dataobjects.html#DeliveryOptions[DeliveryOptions]`|
+++
Set the Event Bus Delivery options used to communicate with Knot's
+++
|[[displayExceptionDetails]]`displayExceptionDetails`|`Boolean`|
+++
Set whether to display or not the exception on error pages
+++
|[[fileUploadDirectory]]`fileUploadDirectory`|`String`|
+++
Set the location on Knot.x environment when uploaded files will be stored. These must be an absolute path.
+++
|[[fileUploadLimit]]`fileUploadLimit`|`Number (Long)`|
+++
Set the file upload limit in bytes
+++
|[[serverOptions]]`serverOptions`|`link:dataobjects.html#HttpServerOptions[HttpServerOptions]`|
+++
Set the HTTP Server options
+++
|===

[[MethodRoutingEntries]]
== MethodRoutingEntries

++++
 Describes a collection of server routing entries
++++
'''

[cols=">25%,^25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[items]]`items`|`Array of link:dataobjects.html#RoutingEntry[RoutingEntry]`|
+++
Sets the list of routing entries
+++
|===

[[RepositoryEntry]]
== RepositoryEntry


[cols=">25%,^25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[address]]`address`|`String`|
+++
Event bus address of the Repository Connector modules, that should deliver content for the requested path matching the regexp in path
+++
|[[doProcessing]]`doProcessing`|`Boolean`|
+++
Defines if the given repository path should be processed by the Knots or not. If not set, a processing is enabled by default.
+++
|[[path]]`path`|`String`|
+++
Sets the Regular expression of the HTTP Request path
+++
|===

[[RoutingEntry]]
== RoutingEntry

++++
 Describes a routing entry of Knot.x Server
++++
'''

[cols=">25%,^25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[address]]`address`|`String`|
+++
Sets the event bus address of the Knot that should process the request for a given path
+++
|[[csrf]]`csrf`|`Boolean`|
+++
Enables/Disabled CSRF support for a given routing entry
+++
|[[onTransition]]`onTransition`|`link:dataobjects.html#RoutingEntry[RoutingEntry]`|
+++
Describes routing to addresses of other Knots based on the transition trigger returned from current Knot.
 <code>"onTransition": {
    "go-a": {</code>,
    "go-b": {}
   }
 }
+++
|[[path]]`path`|`String`|
+++
Sets the Regular expression of HTTP Request path
+++
|===

