= Cheatsheets

[[ServiceKnotOptions]]
== ServiceKnotOptions

++++
 Describes Service Knot configuration
++++
'''

[cols=">25%,25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[address]]`@address`|`String`|+++
Sets the EB address of the verticle. Default is 'knotx.knot.service'
+++
|[[deliveryOptions]]`@deliveryOptions`|`link:dataobjects.html#DeliveryOptions[DeliveryOptions]`|+++
Sets the Vert.x EventBusDeliveryOptions for a given verticle
+++
|[[services]]`@services`|`Array of link:dataobjects.html#ServiceMetadata[ServiceMetadata]`|+++
Sets the mapping between service aliases and service adapters that will serve the data.
+++
|===

[[ServiceMetadata]]
== ServiceMetadata

++++
 Describes a physical details of HTTP service endpoint the ServiceAdapter will use.
++++
'''

[cols=">25%,25%,50%"]
[frame="topbot"]
|===
^|Name | Type ^| Description
|[[address]]`@address`|`String`|+++
Sets the EB address of the service adapter
+++
|[[cacheKey]]`@cacheKey`|`String`|+++
Set the cache key
+++
|[[name]]`@name`|`String`|+++
Set the name of the service the will be used on html snippet level.
+++
|[[params]]`@params`|`Json object`|+++
Set the service parameters to be consumed by the adapter.
+++
|===

